### ISSUE TITLE
Bluetooth reliability

### ISSUE THREAD

**Issue by doesitscript** [Onskreen/cornerstone#7]
Bluetooth has trouble connecting to devices.  

Trying to connect to a device that asks to match the pairing numbers on both devices (e.g. Device1 displays "567890, confirm that this is the same number being displayed on [Cornerstone] Device2.  In this case, the cornerstone device never offers the popup confirmation box that offers to accept the pairing request.  

I have been able to backup blue tooth pairing using titanium backup and have am able to connect to the bluetooth devices.  This only works until they are disconnected at which time the original problem persists.  

Keyboards do not have problems from what I have found.

**Comment by onshm** [comment]
This is confirmed to be a ROM specific issue, not specific to Cornerstone.
